site_name: ALL Detection System For Oculus Rift
site_url: https://www.leukemiaairesearch.com/research/project/peter-moss-medtech-research-project/all-detection-system-for-oculus-rift

nav:
    - Home: 'index.md'
    - Installation:
      - Installation (Windows): 'installation/windows.md'
    - Usage:
      - Usage (Windows): 'usage/windows.md'